zookeeper1:
  image: digitalwonderland/zookeeper
  container_name: zookeeper1
  environment:
    - ZOOKEEPER_ID=1
    - ZOOKEEPER_SERVER_1={VM1_IPAddr}
    - ZOOKEEPER_SERVER_2={VM2_IPAddr}
    - ZOOKEEPER_SERVER_3={VM3_IPAddr}
    - ZOOKEEPER_CLIENT_PORT=2181
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


zookeeper2:
  image: digitalwonderland/zookeeper
  container_name: zookeeper2
  environment:
    - ZOOKEEPER_ID=2
    - ZOOKEEPER_SERVER_1={VM1_IPAddr}
    - ZOOKEEPER_SERVER_2={VM2_IPAddr}
    - ZOOKEEPER_SERVER_3={VM3_IPAddr}
    - ZOOKEEPER_CLIENT_PORT=2181
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


zookeeper3:
  image: digitalwonderland/zookeeper
  container_name: zookeeper3
  environment:
    - ZOOKEEPER_ID=3
    - ZOOKEEPER_SERVER_1={VM1_IPAddr}
    - ZOOKEEPER_SERVER_2={VM2_IPAddr}
    - ZOOKEEPER_SERVER_3={VM3_IPAddr}
    - ZOOKEEPER_CLIENT_PORT=2181
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka1:
  image: wurstmeister/kafka
  container_name: kafka1
  environment:
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ADVERTISED_HOST_NAME={VM1_IPAddr}
    - KAFKA_ZOOKEEPER_CONNECT={VM1_IPAddr}:2181,{VM2_IPAddr}:2181,{VM3_IPAddr}:2181
    - KAFKA_LOG_RETENTION_HOURS=4
    - KAFKA_LOG_RETENTION_BYTES=1000000000
  ports:
    - 9092:9092


kafka2:
  image: wurstmeister/kafka
  container_name: kafka2
  environment:
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ADVERTISED_HOST_NAME={VM2_IPAddr}
    - KAFKA_ZOOKEEPER_CONNECT={VM1_IPAddr}:2181,{VM2_IPAddr}:2181,{VM3_IPAddr}:2181
    - KAFKA_LOG_RETENTION_HOURS=4
    - KAFKA_LOG_RETENTION_BYTES=1000000000
  ports:
    - 9092:9092


kafka3:
  image: wurstmeister/kafka
  container_name: kafka3
  environment:
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ADVERTISED_HOST_NAME={VM3_IPAddr}
    - KAFKA_ZOOKEEPER_CONNECT={VM1_IPAddr}:2181,{VM2_IPAddr}:2181,{VM3_IPAddr}:2181
    - KAFKA_LOG_RETENTION_HOURS=4
    - KAFKA_LOG_RETENTION_BYTES=1000000000
  ports:
    - 9092:9092